display_name: 云联局域网快传
packager: Tienisto
packagerEmail: dev.tien.donam@gmail.com
url: https://github.com/Yunconnect/YunLanTransfer
buildArch: x86_64
license: Apache-2.0

icon: assets/img/logo-512.png

requires:
  - libappindicator
  - xdg-user-dirs

keywords:
  - Sharing
  - LAN
  - Files

generic_name: Secure local network file transfer
summary: Securely transfer files on your local network with 云联局域网快传
group: Applications/Utilities

categories:
  - GTK
  - FileTransfer
  - Utility

startup_notify: true
